// Welcome to the feedback-loop example!
//
// This is based on the triangle-util example, but shows the use of Input attachments to create
// "feedback loops". This technique allows fragments to observe the contents of the framebuffer
// sample they are about to overwrite.
//
// This example assumes that you are already more or less familiar with graphics programming and
// that you want to learn Vulkan. This means that for example it won't go into details about what a
// vertex or a shader is.

use std::{error::Error, sync::Arc, time::Duration};
use vulkano::{
    buffer::{Buffer, BufferContents, BufferCreateInfo, BufferUsage},
    command_buffer::{
        allocator::StandardCommandBufferAllocator, CommandBufferBeginInfo, CommandBufferLevel,
        CommandBufferUsage, RecordingCommandBuffer, RenderPassBeginInfo, SubpassBeginInfo,
        SubpassContents,
    },
    descriptor_set::{
        allocator::{DescriptorSetAllocator, StandardDescriptorSetAllocator},
        layout::{
            DescriptorSetLayout, DescriptorSetLayoutBinding, DescriptorSetLayoutCreateInfo,
            DescriptorType,
        },
        DescriptorSet, WriteDescriptorSet,
    },
    image::{view::ImageView, ImageUsage},
    memory::allocator::{AllocationCreateInfo, MemoryTypeFilter},
    pipeline::{
        graphics::{
            color_blend::{ColorBlendAttachmentState, ColorBlendState},
            input_assembly::InputAssemblyState,
            multisample::MultisampleState,
            rasterization::RasterizationState,
            vertex_input::{Vertex, VertexDefinition},
            viewport::{Viewport, ViewportState},
            GraphicsPipelineCreateInfo,
        },
        layout::{PipelineDescriptorSetLayoutCreateInfo, PipelineLayoutCreateInfo},
        DynamicState, GraphicsPipeline, PipelineBindPoint, PipelineLayout,
        PipelineShaderStageCreateInfo,
    },
    render_pass::{Framebuffer, FramebufferCreateInfo, RenderPass, Subpass},
    shader::ShaderStages,
    sync::GpuFuture,
};
use vulkano_util::{
    context::{VulkanoConfig, VulkanoContext},
    window::VulkanoWindows,
};
use winit::{
    event::{Event, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
};

fn main() -> Result<(), impl Error> {
    let context = VulkanoContext::new(VulkanoConfig::default());
    let event_loop = EventLoop::new().unwrap();
    // Manages any windows and their rendering.
    let mut windows_manager = VulkanoWindows::default();
    windows_manager.create_window(&event_loop, &context, &Default::default(), |create_info| {
        // We need to use the swapchain images for feedback, which is Color + Input usages.
        create_info.image_usage |= ImageUsage::COLOR_ATTACHMENT | ImageUsage::INPUT_ATTACHMENT;
    });
    let window_renderer = windows_manager.get_primary_renderer_mut().unwrap();

    // Some little debug infos.
    println!(
        "Using device: {} (type: {:?})",
        context.device().physical_device().properties().device_name,
        context.device().physical_device().properties().device_type,
    );

    // We now create a buffer that will store the shape of our triangle. We use `#[repr(C)]` here
    // to force rustc to use a defined layout for our data, as the default representation has *no
    // guarantees*.
    #[derive(BufferContents, Vertex)]
    #[repr(C)]
    struct Vertex {
        #[format(R32G32_SFLOAT)]
        position: [f32; 2],
    }

    let vertices = [
        Vertex {
            position: [-0.5, -0.25],
        },
        Vertex {
            position: [0.0, 0.5],
        },
        Vertex {
            position: [0.25, -0.1],
        },
    ];
    let vertex_buffer = Buffer::from_iter(
        context.memory_allocator().clone(),
        BufferCreateInfo {
            usage: BufferUsage::VERTEX_BUFFER,
            ..Default::default()
        },
        AllocationCreateInfo {
            memory_type_filter: MemoryTypeFilter::PREFER_DEVICE
                | MemoryTypeFilter::HOST_SEQUENTIAL_WRITE,
            ..Default::default()
        },
        vertices,
    )
    .unwrap();

    // The next step is to create the shaders.
    //
    // The raw shader creation API provided by the vulkano library is unsafe for various reasons,
    // so The `shader!` macro provides a way to generate a Rust module from GLSL source - in the
    // example below, the source is provided as a string input directly to the shader, but a path
    // to a source file can be provided as well. Note that the user must specify the type of shader
    // (e.g. "vertex", "fragment", etc.) using the `ty` option of the macro.
    //
    // The items generated by the `shader!` macro include a `load` function which loads the shader
    // using an input logical device. The module also includes type definitions for layout
    // structures defined in the shader source, for example uniforms and push constants.
    //
    // A more detailed overview of what the `shader!` macro generates can be found in the
    // vulkano-shaders crate docs. You can view them at https://docs.rs/vulkano-shaders/
    mod vs {
        vulkano_shaders::shader! {
            ty: "vertex",
            src: r"
                #version 450

                layout(location = 0) in vec2 position;

                void main() {
                    gl_Position = vec4(position, 0.0, 1.0);
                }
            ",
        }
    }

    mod fs {
        vulkano_shaders::shader! {
            ty: "fragment",
            src: r"
                #version 450

                layout(location = 0) out vec4 f_color;

                void main() {
                    f_color = vec4(1.0, 0.0, 0.0, 1.0);
                }
            ",
        }
    }

    // This fragment shader utilizes feedback to read the framebuffer before the fragment is
    // overwritten. This is an unsafe operation, as if a single `draw*` operation with this
    // pipeline touches any sample more than once, it becomes a data race - undefined behavior!
    // Since we only draw one triangle, no sample is touched more than once.
    mod feedback_fs {
        vulkano_shaders::shader! {
            ty: "fragment",
            src: r"
                #version 450
                layout(input_attachment_index = 0, set = 0, binding = 0) uniform subpassInput feedback;
                layout(location = 0) out vec4 f_color;

                void main() {
                    // Rotate the color channels of the image we're rendering to
                    // Red becomes blue, blue becomes green, green becomes red.
                    f_color = subpassLoad(feedback).gbra;
                }
            ",
        }
    }

    // Create a render pass manually. This gives us access to Input attachments, which is needed
    // for fragment feedback loops.
    let render_pass = {
        let feedback_attachment = vulkano::render_pass::AttachmentDescription {
            // When using feedback loops, the only viable layout is `General`.
            // (in unextended vulkan)
            initial_layout: vulkano::image::ImageLayout::General,
            final_layout: vulkano::image::ImageLayout::General,
            format: window_renderer.swapchain_format(),
            load_op: vulkano::render_pass::AttachmentLoadOp::Clear,
            store_op: vulkano::render_pass::AttachmentStoreOp::Store,
            ..Default::default()
        };
        // Create two attachment references to the same attachment,
        // allowing it to be used as input *and* output.
        let input_reference = vulkano::render_pass::AttachmentReference {
            attachment: 0,
            aspects: vulkano::image::ImageAspects::COLOR,
            layout: vulkano::image::ImageLayout::General,
            ..Default::default()
        };
        let color_reference = vulkano::render_pass::AttachmentReference {
            attachment: 0,
            aspects: vulkano::image::ImageAspects::empty(),
            layout: vulkano::image::ImageLayout::General,
            ..Default::default()
        };
        let subpass = vulkano::render_pass::SubpassDescription {
            input_attachments: vec![Some(input_reference)],
            color_attachments: vec![Some(color_reference)],
            ..Default::default()
        };

        vulkano::render_pass::RenderPass::new(
            context.device().clone(),
            vulkano::render_pass::RenderPassCreateInfo {
                attachments: vec![feedback_attachment],
                subpasses: vec![subpass],
                ..Default::default()
            },
        )
        .unwrap()
    };

    // We have to indicate which subpass of which render pass the pipeline is going to be used
    // in. The pipeline will only be usable from this particular subpass. We only have one!
    let subpass = Subpass::from(render_pass.clone(), 0).unwrap();

    // Create the layout for our two pipes.
    let pipeline_layout = {
        // Accept an input attachment at set 0, binding 0.
        // Used by `feedback_fs`
        let descriptor_layout = DescriptorSetLayout::new(
            context.device().clone(),
            DescriptorSetLayoutCreateInfo {
                bindings: [(
                    0,
                    DescriptorSetLayoutBinding {
                        stages: ShaderStages::FRAGMENT,
                        ..DescriptorSetLayoutBinding::descriptor_type(
                            DescriptorType::InputAttachment,
                        )
                    },
                )]
                .into_iter()
                .collect(),
                ..Default::default()
            },
        )
        .unwrap();

        PipelineLayout::new(
            context.device().clone(),
            PipelineLayoutCreateInfo {
                set_layouts: vec![descriptor_layout],
                ..Default::default()
            },
        )
        .unwrap()
    };

    // Both pipes share a vertex shader.
    let vs = vs::load(context.device().clone())
        .unwrap()
        .entry_point("main")
        .unwrap();

    // Before we draw, we have to create what is called a **pipeline**. A pipeline describes how
    // a GPU operation is to be performed. It is similar to an OpenGL program, but it also contains
    // many settings for customization, all baked into a single object. For drawing, we create
    // a **graphics** pipeline, but there are also other types of pipeline.
    let triangle_pipeline = {
        // First, we load the shaders that the pipeline will use:
        // the vertex shader and the fragment shader.
        //
        // A Vulkan shader can in theory contain multiple entry points, so we have to specify which
        // one.
        let fs = fs::load(context.device().clone())
            .unwrap()
            .entry_point("main")
            .unwrap();

        // Automatically generate a vertex input state from the vertex shader's input interface,
        // that takes a single vertex buffer containing `Vertex` structs.
        let vertex_input_state = Vertex::per_vertex().definition(&vs).unwrap();

        // Make a list of the shader stages that the pipeline will have.
        let stages = [
            PipelineShaderStageCreateInfo::new(vs.clone()),
            PipelineShaderStageCreateInfo::new(fs),
        ];

        // Finally, create the pipeline.
        GraphicsPipeline::new(
            context.device().clone(),
            None,
            GraphicsPipelineCreateInfo {
                stages: stages.into_iter().collect(),
                // How vertex data is read from the vertex buffers into the vertex shader.
                vertex_input_state: Some(vertex_input_state),
                // How vertices are arranged into primitive shapes.
                // The default primitive shape is a triangle.
                input_assembly_state: Some(InputAssemblyState::default()),
                // How primitives are transformed and clipped to fit the framebuffer.
                // We use a resizable viewport, set to draw over the entire window.
                viewport_state: Some(ViewportState::default()),
                // How polygons are culled and converted into a raster of pixels.
                // The default value does not perform any culling.
                rasterization_state: Some(RasterizationState::default()),
                // How multiple fragment shader samples are converted to a single pixel value.
                // The default value does not perform any multisampling.
                multisample_state: Some(MultisampleState::default()),
                // How pixel values are combined with the values already present in the framebuffer.
                // The default value overwrites the old value with the new one, without any
                // blending.
                color_blend_state: Some(ColorBlendState::with_attachment_states(
                    subpass.num_color_attachments(),
                    ColorBlendAttachmentState::default(),
                )),
                // Dynamic states allows us to specify parts of the pipeline settings when
                // recording the command buffer, before we perform drawing.
                // Here, we specify that the viewport should be dynamic.
                dynamic_state: [DynamicState::Viewport].into_iter().collect(),
                subpass: Some(subpass.clone().into()),
                ..GraphicsPipelineCreateInfo::layout(pipeline_layout.clone())
            },
        )
        .unwrap()
    };
    let feedback_pipeline = {
        // First, we load the shaders that the pipeline will use:
        // the vertex shader and the fragment shader.
        //
        // A Vulkan shader can in theory contain multiple entry points, so we have to specify which
        // one.
        let feedback_fs = feedback_fs::load(context.device().clone())
            .unwrap()
            .entry_point("main")
            .unwrap();

        // Automatically generate a vertex input state from the vertex shader's input interface,
        // that takes a single vertex buffer containing `Vertex` structs.
        let vertex_input_state = Vertex::per_vertex().definition(&vs).unwrap();

        // Make a list of the shader stages that the pipeline will have.
        let stages = [
            PipelineShaderStageCreateInfo::new(vs),
            PipelineShaderStageCreateInfo::new(feedback_fs),
        ];

        // We have to indicate which subpass of which render pass this pipeline is going to be used
        // in. The pipeline will only be usable from this particular subpass.
        let subpass = Subpass::from(render_pass.clone(), 0).unwrap();

        // Finally, create the pipeline.
        GraphicsPipeline::new(
            context.device().clone(),
            None,
            GraphicsPipelineCreateInfo {
                stages: stages.into_iter().collect(),
                // How vertex data is read from the vertex buffers into the vertex shader.
                vertex_input_state: Some(vertex_input_state),
                // How vertices are arranged into primitive shapes.
                // The default primitive shape is a triangle.
                input_assembly_state: Some(InputAssemblyState::default()),
                // How primitives are transformed and clipped to fit the framebuffer.
                // We use a resizable viewport, set to draw over the entire window.
                viewport_state: Some(ViewportState::default()),
                // How polygons are culled and converted into a raster of pixels.
                // The default value does not perform any culling.
                rasterization_state: Some(RasterizationState::default()),
                // How multiple fragment shader samples are converted to a single pixel value.
                // The default value does not perform any multisampling.
                multisample_state: Some(MultisampleState::default()),
                // How pixel values are combined with the values already present in the framebuffer.
                // The default value overwrites the old value with the new one, without any
                // blending.
                color_blend_state: Some(ColorBlendState::with_attachment_states(
                    subpass.num_color_attachments(),
                    ColorBlendAttachmentState::default(),
                )),
                // Dynamic states allows us to specify parts of the pipeline settings when
                // recording the command buffer, before we perform drawing.
                // Here, we specify that the viewport should be dynamic.
                dynamic_state: [DynamicState::Viewport].into_iter().collect(),
                subpass: Some(subpass.into()),
                ..GraphicsPipelineCreateInfo::layout(pipeline_layout.clone())
            },
        )
        .unwrap()
    };

    // Dynamic viewports allow us to recreate just the viewport when the window is resized.
    // Otherwise we would have to recreate the whole pipeline.
    let mut viewport = Viewport {
        offset: [0.0, 0.0],
        extent: [0.0, 0.0],
        depth_range: 0.0..=1.0,
    };

    // We need to be able to allocate descriptors for each texture in the swapchain.
    let descriptor_allocator = Arc::new(StandardDescriptorSetAllocator::new(
        context.device().clone(),
        Default::default(),
    ));

    // The render pass we created above only describes the layout of our framebuffers. Before we
    // can draw we also need to create the actual framebuffers.
    //
    // Since we need to draw to multiple images, we are going to create a different framebuffer for
    // each image, as well as a descriptor set for the feedback attachment.
    let mut per_image_data = window_size_dependent_setup(
        window_renderer.swapchain_image_views(),
        render_pass.clone(),
        &mut viewport,
        pipeline_layout.set_layouts()[0].clone(),
        descriptor_allocator.clone(),
    );

    // Before we can start creating and recording command buffers, we need a way of allocating
    // them. Vulkano provides a command buffer allocator, which manages raw Vulkan command pools
    // underneath and provides a safe interface for them.
    let command_buffer_allocator = Arc::new(StandardCommandBufferAllocator::new(
        context.device().clone(),
        Default::default(),
    ));

    // Initialization is finally finished!

    // In the loop below we are going to submit commands to the GPU. Submitting a command produces
    // an object that implements the `GpuFuture` trait, which holds the resources for as long as
    // they are in use by the GPU.

    event_loop.run(move |event, elwt| {
        elwt.set_control_flow(ControlFlow::Poll);

        match event {
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                ..
            } => {
                elwt.exit();
            }
            Event::WindowEvent {
                event: WindowEvent::Resized(_),
                ..
            } => {
                window_renderer.resize();
            }
            Event::WindowEvent {
                event: WindowEvent::RedrawRequested,
                ..
            } => {
                // Do not draw the frame when the screen size is zero. On Windows, this can
                // occur when minimizing the application.
                let image_extent: [u32; 2] = window_renderer.window().inner_size().into();

                if image_extent.contains(&0) {
                    return;
                }

                // Begin rendering by acquiring the gpu future from the window renderer.
                let previous_frame_end = window_renderer
                    .acquire(Some(Duration::from_millis(1)), |swapchain_images| {
                        // Whenever the window resizes we need to recreate everything dependent
                        // on the window size. In this example that
                        // includes the swapchain, the framebuffers
                        // and the dynamic state viewport.
                        per_image_data = window_size_dependent_setup(
                            swapchain_images,
                            render_pass.clone(),
                            &mut viewport,
                            pipeline_layout.set_layouts()[0].clone(),
                            descriptor_allocator.clone(),
                        );
                    })
                    .unwrap();

                // In order to draw, we have to record a *command buffer*. The command buffer object
                // holds the list of commands that are going to be executed.
                //
                // Recording a command buffer is an expensive operation (usually a few hundred
                // microseconds), but it is known to be a hot path in the driver and is expected to
                // be optimized.
                //
                // Note that we have to pass a queue family when we create the command buffer. The
                // command buffer will only be executable on that given queue family.
                let mut builder = RecordingCommandBuffer::new(
                    command_buffer_allocator.clone(),
                    context.graphics_queue().queue_family_index(),
                    CommandBufferLevel::Primary,
                    CommandBufferBeginInfo {
                        usage: CommandBufferUsage::OneTimeSubmit,
                        ..Default::default()
                    },
                )
                .unwrap();

                builder
                    // Before we can draw, we have to *enter a render pass*.
                    .begin_render_pass(
                        RenderPassBeginInfo {
                            // A list of values to clear the attachments with. This list contains
                            // one item for each attachment in the render pass. In this case, there
                            // is only one attachment, and we clear it with a blue color.
                            //
                            // Only attachments that have `AttachmentLoadOp::Clear` are provided
                            // with clear values, any others should use `None` as the clear value.
                            clear_values: vec![Some([0.0, 0.0, 1.0, 1.0].into())],

                            ..RenderPassBeginInfo::framebuffer(
                                per_image_data[window_renderer.image_index() as usize]
                                    .0
                                    .clone(),
                            )
                        },
                        SubpassBeginInfo {
                            // The contents of the first (and only) subpass.
                            // This can be either `Inline` or `SecondaryCommandBuffers`.
                            // The latter is a bit more advanced and is not covered here.
                            contents: SubpassContents::Inline,
                            ..Default::default()
                        },
                    )
                    .unwrap()
                    // We are now inside the first subpass of the render pass.
                    //
                    // TODO: Document state setting and how it affects subsequent draw commands.
                    .set_viewport(0, [viewport.clone()].into_iter().collect())
                    .unwrap()
                    .bind_pipeline_graphics(triangle_pipeline.clone())
                    .unwrap()
                    .bind_vertex_buffers(0, vertex_buffer.clone())
                    .unwrap();

                unsafe {
                    builder
                        // Draw the red triangle normally.
                        .draw(vertex_buffer.len() as u32, 1, 0, 0)
                        .unwrap();
                }
                // Now, switch to the feedback pipe and bind it's input attachment
                builder
                    .bind_pipeline_graphics(feedback_pipeline.clone())
                    .unwrap()
                    .bind_descriptor_sets(
                        PipelineBindPoint::Graphics,
                        pipeline_layout.clone(),
                        0,
                        per_image_data[window_renderer.image_index() as usize]
                            .1
                            .clone(),
                    )
                    .unwrap();

                unsafe {
                    builder
                        // Draw the triangle twice more using feedback shader.
                        // This will rotate the color to be Blue...
                        .draw(vertex_buffer.len() as u32, 1, 0, 0)
                        .unwrap()
                        // .. and then green!
                        .draw(vertex_buffer.len() as u32, 1, 0, 0)
                        .unwrap();
                }

                builder
                    // We leave the render pass. Note that if we had multiple subpasses we could
                    // have called `next_subpass` to jump to the next subpass.
                    .end_render_pass(Default::default())
                    .unwrap();

                // Finish recording the command buffer by calling `end`.
                let command_buffer = builder.end().unwrap();

                let future = previous_frame_end
                    .then_execute(context.graphics_queue().clone(), command_buffer)
                    .unwrap()
                    .boxed();

                // The color output is now expected to contain our triangle. But in order to
                // show it on the screen, we have to *present* the image by calling
                // `present` on the window renderer.
                //
                // This function does not actually present the image immediately. Instead it
                // submits a present command at the end of the queue. This means that it will
                // only be presented once the GPU has finished executing the command buffer
                // that draws the triangle.
                window_renderer.present(future, false);
            }
            Event::AboutToWait => window_renderer.window().request_redraw(),
            _ => (),
        }
    })
}

/// This function is called once during initialization, then again whenever the window is resized.
fn window_size_dependent_setup(
    swapchain_images: &[Arc<ImageView>],
    render_pass: Arc<RenderPass>,
    viewport: &mut Viewport,
    descriptor_layout: Arc<DescriptorSetLayout>,
    descriptor_allocator: Arc<dyn DescriptorSetAllocator>,
) -> Vec<(Arc<Framebuffer>, Arc<DescriptorSet>)> {
    let extent = swapchain_images[0].image().extent();
    viewport.extent = [extent[0] as f32, extent[1] as f32];

    swapchain_images
        .iter()
        .map(|swapchain_image| {
            let framebuffer = Framebuffer::new(
                render_pass.clone(),
                FramebufferCreateInfo {
                    attachments: vec![swapchain_image.clone()],
                    ..Default::default()
                },
            )
            .unwrap();

            // Input attachments use an `image_view` of the relevant framebuffer image for their
            // contents.
            let descriptor = DescriptorSet::new(
                descriptor_allocator.clone(),
                descriptor_layout.clone(),
                [WriteDescriptorSet::image_view(0, swapchain_image.clone())],
                [],
            )
            .unwrap();

            (framebuffer, descriptor)
        })
        .collect()
}
